/**
 * Template Registry
 * Stores project templates for different project types
 */

export const PROJECT_TEMPLATES = {
  "node-api": {
    name: "Node.js REST API",
    description: "Express.js REST API server",
    type: "backend",
    main: "src/index.js",
    startScript: "node src/index.js",
    devScript: "node --watch src/index.js",
    testScript: "node --test src/tests/**/*.test.js",
    dependencies: {
      express: "^4.18.2",
      "dotenv": "^16.3.1",
      "cors": "^2.8.5"
    },
    devDependencies: {
      "nodemon": "^3.0.1"
    },
    structure: `
\`\`\`
src/
  ├── index.js          # Entry point
  ├── routes/           # API routes
  ├── middleware/       # Express middleware
  ├── controllers/      # Request handlers
  └── utils/            # Utility functions
tests/
  └── api.test.js       # Test suite
package.json
.env.example
.gitignore
README.md
\`\`\`
    `,
    template: {
      "src/index.js": `import express from 'express';
import cors from 'cors';

const app = express();
const PORT = process.env.PORT || 3000;

app.use(cors());
app.use(express.json());

// Health check
app.get('/health', (req, res) => {
  res.json({ status: 'ok', timestamp: new Date().toISOString() });
});

// 404 handler
app.use((req, res) => {
  res.status(404).json({ error: 'Not found' });
});

// Start server
app.listen(PORT, () => {
  console.log(\`Server running on http://localhost:\${PORT}\`);
});
`,
      "src/routes/.gitkeep": "",
      "src/middleware/.gitkeep": "",
      "src/controllers/.gitkeep": "",
      "src/utils/.gitkeep": "",
      ".env.example": `PORT=3000
NODE_ENV=development
`
    }
  },

  "react-app": {
    name: "React Web Application",
    description: "React SPA with Vite",
    type: "frontend",
    main: "src/main.jsx",
    startScript: "vite",
    devScript: "vite",
    buildScript: "vite build",
    dependencies: {
      "react": "^18.2.0",
      "react-dom": "^18.2.0"
    },
    devDependencies: {
      "vite": "^5.0.0",
      "@vitejs/plugin-react": "^4.2.0"
    },
    structure: `
\`\`\`
src/
  ├── main.jsx          # Entry point
  ├── App.jsx           # Root component
  ├── components/       # React components
  ├── pages/            # Page components
  └── styles/           # CSS files
public/
  └── index.html        # HTML template
vite.config.js
package.json
.env.example
.gitignore
README.md
\`\`\`
    `,
    template: {
      "src/main.jsx": `import React from 'react'
import ReactDOM from 'react-dom/client'
import App from './App.jsx'

ReactDOM.createRoot(document.getElementById('root')).render(
  <React.StrictMode>
    <App />
  </React.StrictMode>,
)
`,
      "src/App.jsx": `import './App.css'

export default function App() {
  return (
    <div className="container">
      <h1>Welcome to Genie-Generated React App</h1>
      <p>Your app is ready to go!</p>
    </div>
  )
}
`,
      "src/App.css": `body {
  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', 'Roboto', 'Oxygen',
    'Ubuntu', 'Cantarell', 'Fira Sans', 'Droid Sans', 'Helvetica Neue',
    sans-serif;
}

.container {
  max-width: 800px;
  margin: 0 auto;
  padding: 40px 20px;
  text-align: center;
}

h1 {
  color: #333;
  margin-bottom: 20px;
}

p {
  color: #666;
  font-size: 16px;
}
`,
      "public/index.html": `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Genie App</title>
</head>
<body>
  <div id="root"></div>
  <script type="module" src="/src/main.jsx"></script>
</body>
</html>
`,
      "vite.config.js": `import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'

export default defineConfig({
  plugins: [react()],
  server: {
    port: 3000,
    open: true
  }
})
`,
      "src/components/.gitkeep": "",
      "src/pages/.gitkeep": ""
    }
  },

  "browser-game": {
    name: "Browser-Based Game",
    description: "Interactive game using HTML5 Canvas and JavaScript",
    type: "fullstack",
    main: "src/game.js",
    startScript: "npx http-server . -p 3000",
    devScript: "npx http-server . -p 3000",
    dependencies: {
      "http-server": "^14.1.1"
    },
    devDependencies: {},
    structure: `
\`\`\`
src/
  ├── game.js           # Main game logic
  ├── player.js         # Player class
  ├── enemies.js        # Enemy classes
  ├── utils.js          # Utility functions
  └── styles.css        # Game styles
public/
  └── index.html        # Game page
package.json
README.md
\`\`\`
    `,
    template: {
      "public/index.html": `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Browser Game - Generated by Genie</title>
  <link rel="stylesheet" href="../src/styles.css">
</head>
<body>
  <div id="gameContainer">
    <canvas id="gameCanvas"></canvas>
  </div>
  <div id="hud">
    <div id="score">Score: 0</div>
    <div id="instructions">Use Arrow Keys to Move | Space to Action</div>
  </div>
  <script src="../src/utils.js"></script>
  <script src="../src/player.js"></script>
  <script src="../src/enemies.js"></script>
  <script src="../src/game.js"></script>
</body>
</html>
`,
      "src/game.js": `// Game state
const canvas = document.getElementById('gameCanvas');
const ctx = canvas.getContext('2d');

canvas.width = window.innerWidth;
canvas.height = window.innerHeight;

let gameRunning = true;
let score = 0;
let player = null;
let enemies = [];
let projectiles = [];

// Game loop
function update() {
  ctx.fillStyle = '#1a1a1a';
  ctx.fillRect(0, 0, canvas.width, canvas.height);

  if (player) {
    player.update();
    player.draw(ctx);
  }

  // Update enemies
  enemies.forEach((enemy, index) => {
    enemy.update();
    enemy.draw(ctx);
    
    if (enemy.isDead()) {
      enemies.splice(index, 1);
      score += 10;
    }
  });

  // Update HUD
  document.getElementById('score').textContent = 'Score: ' + score;
}

function animate() {
  update();
  if (gameRunning) {
    requestAnimationFrame(animate);
  }
}

// Input handling
document.addEventListener('keydown', (e) => {
  if (player) {
    if (e.key === 'ArrowUp') player.moveUp();
    if (e.key === 'ArrowDown') player.moveDown();
    if (e.key === 'ArrowLeft') player.moveLeft();
    if (e.key === 'ArrowRight') player.moveRight();
    if (e.key === ' ') player.action();
  }
});

// Start game
window.addEventListener('load', () => {
  console.log('Game initialized by Genie!');
  animate();
});
`,
      "src/player.js": `class Player {
  constructor(x, y) {
    this.x = x;
    this.y = y;
    this.width = 30;
    this.height = 30;
    this.speedX = 0;
    this.speedY = 0;
    this.speed = 5;
  }

  moveUp() { this.speedY = -this.speed; }
  moveDown() { this.speedY = this.speed; }
  moveLeft() { this.speedX = -this.speed; }
  moveRight() { this.speedX = this.speed; }

  action() {
    console.log('Player action triggered!');
  }

  update() {
    this.x += this.speedX;
    this.y += this.speedY;
    
    // Boundary checking
    if (this.x < 0) this.x = 0;
    if (this.x + this.width > window.innerWidth) this.x = window.innerWidth - this.width;
    if (this.y < 50) this.y = 50;
    if (this.y + this.height > window.innerHeight) this.y = window.innerHeight - this.height;
    
    this.speedX = 0;
    this.speedY = 0;
  }

  draw(ctx) {
    ctx.fillStyle = '#00ff00';
    ctx.fillRect(this.x, this.y, this.width, this.height);
    ctx.strokeStyle = '#00ff00';
    ctx.lineWidth = 2;
    ctx.strokeRect(this.x, this.y, this.width, this.height);
  }
}
`,
      "src/enemies.js": `class Enemy {
  constructor(x, y) {
    this.x = x;
    this.y = y;
    this.width = 25;
    this.height = 25;
    this.speedX = Math.random() * 2 - 1;
    this.speedY = Math.random() * 2 - 1;
    this.health = 1;
  }

  update() {
    this.x += this.speedX;
    this.y += this.speedY;
    
    // Bounce off walls
    if (this.x < 0 || this.x + this.width > window.innerWidth) {
      this.speedX *= -1;
    }
    if (this.y < 50 || this.y + this.height > window.innerHeight) {
      this.speedY *= -1;
    }
  }

  draw(ctx) {
    ctx.fillStyle = '#ff0000';
    ctx.fillRect(this.x, this.y, this.width, this.height);
  }

  isDead() {
    return this.health <= 0;
  }
}
`,
      "src/utils.js": `function randomRange(min, max) {
  return Math.random() * (max - min) + min;
}

function distance(x1, y1, x2, y2) {
  return Math.sqrt((x2 - x1) ** 2 + (y2 - y1) ** 2);
}

function createEnemy() {
  const x = Math.random() * window.innerWidth;
  const y = Math.random() * window.innerHeight;
  return new Enemy(x, y);
}
`,
      "src/styles.css": `* {
  margin: 0;
  padding: 0;
  box-sizing: border-box;
}

body {
  background: #1a1a1a;
  overflow: hidden;
  font-family: Arial, sans-serif;
}

canvas {
  display: block;
  background: #0a0a0a;
  cursor: crosshair;
}

#hud {
  position: absolute;
  top: 10px;
  left: 10px;
  color: #00ff00;
  font-family: 'Courier New', monospace;
  z-index: 100;
}

#score {
  font-size: 24px;
  margin-bottom: 10px;
  text-shadow: 0 0 10px rgba(0, 255, 0, 0.5);
}

#instructions {
  font-size: 12px;
  color: #00ff00;
  opacity: 0.7;
}
`,
      "package.json": `{
  "name": "browser-game",
  "version": "1.0.0",
  "description": "Browser-based game generated by Genie",
  "scripts": {
    "start": "npx http-server . -p 3000",
    "dev": "npx http-server . -p 3000"
  },
  "dependencies": {
    "http-server": "^14.1.1"
  }
}
`
    }
  },

  "fullstack-app": {
    name: "Full-Stack Application",
    description: "Node.js backend + React frontend",
    type: "fullstack",
    structure: `
\`\`\`
backend/
  ├── src/
  │   ├── index.js
  │   ├── routes/
  │   └── utils/
  └── package.json

frontend/
  ├── src/
  │   ├── main.jsx
  │   ├── App.jsx
  │   └── components/
  ├── public/
  │   └── index.html
  └── package.json

docker-compose.yml      # For containerization
README.md
\`\`\`
    `,
    template: {}
  }
};

export function getTemplate(templateType) {
  return PROJECT_TEMPLATES[templateType] || null;
}

export function listTemplates() {
  return Object.entries(PROJECT_TEMPLATES).map(([key, template]) => ({
    id: key,
    name: template.name,
    description: template.description,
    type: template.type
  }));
}

export default PROJECT_TEMPLATES;
